# Generated by Django 3.2.7 on 2021-09-29 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imovel', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('condicao_pagto', models.IntegerField(choices=[(1, 'À vista'), (180, '180x')], default=1, verbose_name='Condicoes de Pagamento')),
                ('valor_imovel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Imovel')),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comissao')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='cliente.cliente', verbose_name='Cliente')),
                ('imovel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='imovel.imovel', verbose_name='Imovel')),
            ],
            options={
                'ordering': ('vendedor', 'data_inclusao'),
            },
        ),
    ]
