# Generated by Django 3.2.7 on 2021-09-27 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imovel', '0002_auto_20210927_1833'),
        ('cliente', '0002_auto_20210927_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtainclusao', models.DateField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente', verbose_name='Cliente')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='imovel.imovel', verbose_name='Imovel')),
            ],
            options={
                'ordering': ('vendedor', 'dtainclusao'),
            },
        ),
    ]
