# Generated by Django 3.2.7 on 2021-09-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_venda_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='condpagto',
            field=models.IntegerField(default=1, verbose_name='Condicoes de Pagamento'),
        ),
    ]
