# Generated by Django 3.2.7 on 2021-09-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_venda_condpagto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='condpagto',
            field=models.IntegerField(choices=[(1, 'Avista'), (180, '180x')], default=1, verbose_name='Condicoes de Pagamento'),
        ),
    ]
