# Generated by Django 3.2.7 on 2021-09-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True, verbose_name='Descricao')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereco')),
                ('vlrimovel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Imovel')),
                ('vlrcomissao', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Valor Comissao(%)')),
                ('dtainclusao', models.DateField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('tipo', models.BooleanField(choices=[('AP', 'Ativo'), ('LT', 'Inativo')], verbose_name='Tipo')),
                ('status', models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], verbose_name='Status')),
            ],
            options={
                'ordering': ('descricao', 'vlrimovel'),
            },
        ),
    ]
