# Generated by Django 3.2.7 on 2021-09-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('APARTAMENTO', 'Apartamento'), ('LOTE', 'Lote')], max_length=11, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='vlrcomissao',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor Comissao(%)'),
        ),
    ]
