# Generated by Django 3.2.7 on 2021-09-28 15:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0002_auto_20210927_1833'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='imovel',
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
    ]
