# Generated by Django 3.2.7 on 2021-09-29 15:10

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email')),
                ('cpf', models.CharField(db_index=True, max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('dtainclusao', models.DateField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('status', models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], verbose_name='Status')),
            ],
            options={
                'ordering': ('nome', 'dtainclusao'),
            },
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
    ]
