# Generated by Django 3.2.7 on 2021-09-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], verbose_name='Status'),
        ),
    ]
